// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_zajb3AFByI13rkp3ufV5KJvr3d40dk',
    appId: '1:505681619382:web:2334cb0138ff3a99087917',
    messagingSenderId: '505681619382',
    projectId: 'flutterauthyt',
    authDomain: 'flutterauthyt.firebaseapp.com',
    storageBucket: 'flutterauthyt.appspot.com',
    measurementId: 'G-1VG4NPYZGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rShsBmjrdFruDT-cw85CMaEvcGD9-z8',
    appId: '1:505681619382:android:f02b9e71578c0c27087917',
    messagingSenderId: '505681619382',
    projectId: 'flutterauthyt',
    storageBucket: 'flutterauthyt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ganZXy9_Nz83g7d1-nqzq18Zk5IsOas',
    appId: '1:505681619382:ios:2958c139bd569c66087917',
    messagingSenderId: '505681619382',
    projectId: 'flutterauthyt',
    storageBucket: 'flutterauthyt.appspot.com',
    iosBundleId: 'com.example.flutterAuthYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ganZXy9_Nz83g7d1-nqzq18Zk5IsOas',
    appId: '1:505681619382:ios:ab51fef452075dc9087917',
    messagingSenderId: '505681619382',
    projectId: 'flutterauthyt',
    storageBucket: 'flutterauthyt.appspot.com',
    iosBundleId: 'com.example.flutterAuthYt.RunnerTests',
  );
}
